In [1]:
import math

In [2]:
def basic_sigmoid(x):
    return 1/(1+math.exp(-x))


In [3]:
print(basic_sigmoid(3))

0.9525741268224334


In [6]:
import numpy as np
x = np.array([1,2,3])
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692]


In [19]:
x = np.array([1,2,3])
print(x + 3)

def sigmoid(x):
    return 1/(1+np.exp(-x))

[4 5 6]


In [28]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1-s)

In [29]:
a = np.array([1,2,3])
sigmoid_derivative(a)

array([0.19661193, 0.10499359, 0.04517666])

In [36]:
# GradeFunction  image2vector
def image2vector(image):
    return image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)

image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

vec = image2vector(image)
vec

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

In [37]:
# 归一化
def normalizeRows(x):
    return  x / np.linalg.norm(x, ord=2, axis=1, keepdims=True)

x = np.array([
    [0, 3, 4],
    [1, 6, 4]])

normalizeRows(x)

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

In [38]:
# softmax
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=1,keepdims=True)

x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [49]:
# Funciton L1
def L1(yhat, y):
    return np.sum(abs(yhat - y))

In [50]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 1.1


In [52]:
# Function L2
def L2(yhat, y):
    return np.sum(np.dot((yhat-y),(yhat-y)))

In [53]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
